### ISSUE TITLE
set large screen?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/ez-modal#2]
how to set large screen?

**Comment by IstoraMandiri** [comment]
This can achieved by setting a class to the modal using the `classes` parameter, which you can then target with CSS to change the width and height.

TODO: I'm leaving this issue open because right now the `classes` option targets the modal wrapper, so I'm thinking of adding a `size` field to cater for http://getbootstrap.com/javascript/#modals-sizes.

**Comment by IstoraMandiri** [comment]
You can now use `size: 'lg'` or `size: 'sm'` to increase and decrease the width of the modal.
